### ISSUE TITLE
Latest commit missing

### ISSUE THREAD

**Issue by jimib** [GeorgeWL/Weather-App#1]
Hi George

I think you've not pushed your latest code. Might be my browser failing to render content, but your medium post shows the weather component which is missing here. Last pushed commit was 3 days ago.

Thanks

Jimi@Pixel

**Comment by GeorgeWL** [comment]
not sure why it didn't push to be honest. my internet is terrible here sometimes so maybe it failed then didn't give an `error failed to commit` for some silly reason @jimib 

Should be sorted now 👍
